// Code generated by "stringer -type month"; DO NOT EDIT.

package calendar

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[January-0]
	_ = x[February-1]
	_ = x[March-2]
	_ = x[April-3]
	_ = x[May-4]
	_ = x[June-5]
	_ = x[July-6]
	_ = x[August-7]
	_ = x[September-8]
	_ = x[October-9]
	_ = x[November-10]
	_ = x[December-11]
}

const _month_name = "JanuaryFebruaryMarchAprilMayJuneJulyAugustSeptemberOctoberNovemberDecember"

var _month_index = [...]uint8{0, 7, 15, 20, 25, 28, 32, 36, 42, 51, 58, 66, 74}

func (i month) String() string {
	if i < 0 || i >= month(len(_month_index)-1) {
		return "month(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _month_name[_month_index[i]:_month_index[i+1]]
}
